// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Get provides a mock function with given fields: apiKey, search, location, radiusMiles, page, jobsPerPage, daysAgo, refineSalary
func (_m *Client) Get(apiKey string, search string, location string, radiusMiles string, page string, jobsPerPage string, daysAgo string, refineSalary string) ([]byte, int, error) {
	ret := _m.Called(apiKey, search, location, radiusMiles, page, jobsPerPage, daysAgo, refineSalary)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string, string, string, string, string, string, string, string) []byte); ok {
		r0 = rf(apiKey, search, location, radiusMiles, page, jobsPerPage, daysAgo, refineSalary)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(string, string, string, string, string, string, string, string) int); ok {
		r1 = rf(apiKey, search, location, radiusMiles, page, jobsPerPage, daysAgo, refineSalary)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string, string, string, string, string, string, string, string) error); ok {
		r2 = rf(apiKey, search, location, radiusMiles, page, jobsPerPage, daysAgo, refineSalary)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
